#!/bin/sh
set -eu

# L4 SNI TCP redirect: route by SNI to external IP:port.
#
# ROUTES lines:
#   *.example.com=1.1.1.1:443          → zone + auto xhttp-*.example.com → IP:XHTTP_PORT
#   special.example.com=2.2.2.2:443    → exact SNI only (no auto xhttp)
#
# Match order: xhttp-* (zones) → exact FQDN → *.zone. Unknown SNI → reject.

: "${LISTEN_PORT:=443}"
: "${XHTTP_PORT:=8443}"
: "${ROUTES:?ROUTES is required (e.g. '*.example.com=1.1.1.1:443')}"
RENDERED="/tmp/haproxy.cfg"
STATE="$(mktemp -d)"
trap 'rm -rf "$STATE"' EXIT

escape_dots() {
  printf '%s' "$1" | sed 's/\./\\./g'
}

route_id() {
  printf '%s' "$1" | tr '.-' '_' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_]//g'
}

valid_backend() {
  printf '%s' "$1" | grep -Eq '^[A-Za-z0-9._-]+:[0-9]+$'
}

valid_fqdn() {
  printf '%s' "$1" | grep -Eq '^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$'
}

TMP_ROUTES="$STATE/routes"
printf '%s\n' "$ROUTES" | tr ';' '\n' | sed -e 's/#.*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d' > "$TMP_ROUTES"

if [ ! -s "$TMP_ROUTES" ]; then
  echo "ROUTES is empty after parsing" >&2
  exit 1
fi

: > "$STATE/kinds"
: > "$STATE/names"
: > "$STATE/hosts"
: > "$STATE/ports"
: > "$STATE/ids"
IDX=0

while IFS= read -r line || [ -n "$line" ]; do
  case "$line" in
    *=*) ;;
    *)
      echo "Invalid ROUTES line (expected pattern=host:port): $line" >&2
      exit 1
      ;;
  esac

  pattern="${line%%=*}"
  backend="${line#*=}"

  if [ -z "$pattern" ] || [ -z "$backend" ]; then
    echo "Invalid ROUTES line: $line" >&2
    exit 1
  fi

  if ! valid_backend "$backend"; then
    echo "Invalid backend (host:port): $backend" >&2
    exit 1
  fi

  host="${backend%:*}"
  port="${backend##*:}"

  case "$pattern" in
    \*.*)
      kind="zone"
      name="${pattern#\*.}"
      ;;
    *)
      kind="exact"
      name="$pattern"
      if ! valid_fqdn "$name"; then
        echo "Invalid exact SNI: $name" >&2
        exit 1
      fi
      ;;
  esac

  if [ -z "$name" ]; then
    echo "Invalid ROUTES line: $line" >&2
    exit 1
  fi

  id="$(route_id "$name")"
  if [ -z "$id" ]; then
    echo "Cannot derive id from: $name" >&2
    exit 1
  fi

  printf '%s\n' "$kind" >> "$STATE/kinds"
  printf '%s\n' "$name" >> "$STATE/names"
  printf '%s\n' "$host" >> "$STATE/hosts"
  printf '%s\n' "$port" >> "$STATE/ports"
  printf '%s\n' "$id" >> "$STATE/ids"
  IDX=$((IDX + 1))
done < "$TMP_ROUTES"

if [ "$IDX" -eq 0 ]; then
  echo "No valid routes parsed from ROUTES" >&2
  exit 1
fi

{
  cat <<EOF
# Generated by docker-entrypoint.sh — do not edit.
# Zone routes auto-add xhttp-* → IP:${XHTTP_PORT}. Exact SNI has no auto xhttp.

global
    # warning+: no per-connection tcplog (keeps docker logs small)
    log stdout format raw local0 warning
    maxconn 200000
    # nbthread omitted: HAProxy auto-sets threads to available CPUs.
    tune.bufsize 32768
    tune.maxrewrite 1024

defaults
    mode tcp
    log global
    option dontlognull
    timeout connect 5s
    timeout client  300s
    timeout server  300s
    timeout tunnel  1h

frontend fe_tls
    bind :${LISTEN_PORT}
    tcp-request inspect-delay 5s
EOF

  # ACLs: xhttp (zones) → exact → zone
  i=1
  while [ "$i" -le "$IDX" ]; do
    kind="$(sed -n "${i}p" "$STATE/kinds")"
    name="$(sed -n "${i}p" "$STATE/names")"
    id="$(sed -n "${i}p" "$STATE/ids")"
    if [ "$kind" = "zone" ]; then
      name_re="$(escape_dots "$name")"
      printf '    acl is_xhttp_%s req_ssl_sni -m reg -i ^xhttp-.+\\.%s$\n' "$id" "$name_re"
    fi
    i=$((i + 1))
  done

  i=1
  while [ "$i" -le "$IDX" ]; do
    kind="$(sed -n "${i}p" "$STATE/kinds")"
    name="$(sed -n "${i}p" "$STATE/names")"
    id="$(sed -n "${i}p" "$STATE/ids")"
    if [ "$kind" = "exact" ]; then
      printf '    acl is_exact_%s req_ssl_sni -i %s\n' "$id" "$name"
    fi
    i=$((i + 1))
  done

  i=1
  while [ "$i" -le "$IDX" ]; do
    kind="$(sed -n "${i}p" "$STATE/kinds")"
    name="$(sed -n "${i}p" "$STATE/names")"
    id="$(sed -n "${i}p" "$STATE/ids")"
    if [ "$kind" = "zone" ]; then
      printf '    acl is_zone_%s req_ssl_sni -m end -i .%s\n' "$id" "$name"
    fi
    i=$((i + 1))
  done

  printf '    tcp-request content accept if { req_ssl_hello_type 1 }\n'
  printf '    tcp-request content reject if { req_ssl_hello_type 1 }'
  i=1
  while [ "$i" -le "$IDX" ]; do
    kind="$(sed -n "${i}p" "$STATE/kinds")"
    id="$(sed -n "${i}p" "$STATE/ids")"
    if [ "$kind" = "zone" ]; then
      printf ' !is_xhttp_%s !is_zone_%s' "$id" "$id"
    else
      printf ' !is_exact_%s' "$id"
    fi
    i=$((i + 1))
  done
  printf '\n'

  # use_backend order: xhttp → exact → zone
  i=1
  while [ "$i" -le "$IDX" ]; do
    kind="$(sed -n "${i}p" "$STATE/kinds")"
    id="$(sed -n "${i}p" "$STATE/ids")"
    if [ "$kind" = "zone" ]; then
      printf '    use_backend be_xhttp_%s if is_xhttp_%s\n' "$id" "$id"
    fi
    i=$((i + 1))
  done

  i=1
  while [ "$i" -le "$IDX" ]; do
    kind="$(sed -n "${i}p" "$STATE/kinds")"
    id="$(sed -n "${i}p" "$STATE/ids")"
    if [ "$kind" = "exact" ]; then
      printf '    use_backend be_exact_%s if is_exact_%s\n' "$id" "$id"
    fi
    i=$((i + 1))
  done

  i=1
  while [ "$i" -le "$IDX" ]; do
    kind="$(sed -n "${i}p" "$STATE/kinds")"
    id="$(sed -n "${i}p" "$STATE/ids")"
    if [ "$kind" = "zone" ]; then
      printf '    use_backend be_zone_%s if is_zone_%s\n' "$id" "$id"
    fi
    i=$((i + 1))
  done

  printf '\n'

  i=1
  while [ "$i" -le "$IDX" ]; do
    kind="$(sed -n "${i}p" "$STATE/kinds")"
    host="$(sed -n "${i}p" "$STATE/hosts")"
    port="$(sed -n "${i}p" "$STATE/ports")"
    id="$(sed -n "${i}p" "$STATE/ids")"
    if [ "$kind" = "zone" ]; then
      cat <<EOF
backend be_xhttp_${id}
    mode tcp
    server s1 ${host}:${XHTTP_PORT}

backend be_zone_${id}
    mode tcp
    server s1 ${host}:${port}

EOF
    else
      cat <<EOF
backend be_exact_${id}
    mode tcp
    server s1 ${host}:${port}

EOF
    fi
    i=$((i + 1))
  done
} > "$RENDERED"

echo "multipass redirect: ${IDX} route(s), listen :${LISTEN_PORT}, xhttp port ${XHTTP_PORT}"
exec haproxy -f "$RENDERED" -db "$@"
